In [1]:
# Packages
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from matplotlib import pyplot
import numpy as np
import pandas as pd
import seaborn
import sys
# Open flood_tool package
sys.path.append('../..')
import flood_tool as ft

In [2]:
## Opening Dataset

In [3]:
# Open dataset
DF_orig = pd.read_csv("../resources/sector_data.csv")
DF_orig

     postcodeSector  households  numberOfPostcodeUnits  headcount
0            AL1  1        2546                    311       6080
1            AL1  2        2642                    236       6942
2            AL1  3        2272                    388       5821
3            AL1  4        3707                    339       9635
4            AL1  5        4406                    347      10560
...             ...         ...                    ...        ...
7547         NP16 7        2435                    203       6299
7548         NP25 3        2425                      5       4918
7549         NP25 4        1460                     17       3871
7550         NP25 5        2862                     15       7162
7551         NP7  8        1348                      2       3083

[7552 rows x 4 columns]

In [4]:
# Calculate percentage of missing values in each column
missing = DF_orig.isnull().sum() / len(DF_orig)
missing

postcodeSector           0.0
households               0.0
numberOfPostcodeUnits    0.0
headcount                0.0
dtype: float64

In [5]:
# Statistics
DF_orig.describe()

        households  numberOfPostcodeUnits     headcount
count  7552.000000            7552.000000   7552.000000
mean   3055.941075             251.155985   7477.217558
std    1568.393581              90.448864   4068.055719
min      52.000000               1.000000     26.000000
25%    1873.250000             198.000000   4412.750000
50%    3014.500000             264.000000   7262.000000
75%    4131.000000             318.000000  10132.250000
max    9894.000000             400.000000  25862.000000

## Getting Postcode District

In [6]:
# Function to get postcode district from postcode
def Postcode_District(Postcode):
# Normal scenario
    if " " in Postcode:
        Split = Postcode.split()
        District = Split[0].upper()
# Bad formatting
    else:
        Outward = Postcode[:-1].strip("_").strip("-").strip("+")
        District = Outward.upper()
    return (District)

In [7]:
# Add postcode district and postcode sector into dataframe
def Add_Postcode_District(DF_orig):
    DF = DF_orig.copy()
    Districts = []
# Find postcode district for each postcode sector in dataframe
    for i in range(len(DF)):
        Districts.append(Postcode_District(DF['postcodeSector'][i]))
# Add new column to dataframe
    DF['postcodeDistrict'] = Districts
    return (DF)
# Apply function
DF_updated = Add_Postcode_District(DF_orig)
DF_updated

,postcodeSector,households,numberOfPostcodeUnits,headcount,postcodeDistrict
0,AL1 1,2546,311,6080,AL1
1,AL1 2,2642,236,6942,AL1
2,AL1 3,2272,388,5821,AL1
3,AL1 4,3707,339,9635,AL1
4,AL1 5,4406,347,10560,AL1
...,...,...,...,...,...
7547,NP16 7,2435,203,6299,NP16
7548,NP25 3,2425,5,4918,NP25
7549,NP25 4,1460,17,3871,NP25
7550,NP25 5,2862,15,7162,NP25
7551,NP7 8,1348,2,3083,NP7

## Outputting Preprocessed Data

In [8]:
# Define output directory
Output_Diri = '../resources/preprocessed_data/'

In [9]:
# Output preprocessed data as new csv file
DF_updated.to_csv(Output_Diri+'sector_preprocessed.csv', index=False)